import { useState, useEffect } from "react";
import { Card, FormField, Loader } from "../../Components";

type PostType = {};

const Home = () => {
  const [loading, setLoading] = useState<boolean>();
  const [allPosts, setAllPosts] = useState<PostType[]>([]);
  return (
    <section className=" max-w-7xl mx-auto ">
      <div>
        <h1 className=" font-extrabold text-[#222328] text-[32px]">
          The Community Showcase
        </h1>
        <p className=" mt-2 text-[#666e75] text-[16px] max-w-[500px]">
          Browse Through a Collection of Imaginative and Visually Stunning
          Images Generated By Dally AI
        </p>
      </div>
      <div className=" mt-16s">
        <FormField />
      </div>
      <div className=" mt-10">
        {loading ? (
          <div className=" flex justify-center items-center">
            <Loader />
          </div>
        ) : null}
      </div>
    </section>
  );
};

export default Home;
